[workspace]
members = [
    "crates/wami-core",
    "crates/wami-traits",
    "crates/wami-provider",
    "crates/cloud-provider/wami-provider-aws",
    "crates/cloud-provider/wami-provider-gcp",
    "crates/cloud-provider/wami-provider-azure",
    "crates/cloud-provider/wami-provider-custom",
    "crates/wami-credentials",
    "crates/wami-service",
    "crates/wami",
    "crates/wami-macros",
]

resolver = "2"
