[package]
name = "wami-provider-azure"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Microsoft Azure provider implementation for WAMI"

[dependencies]
uuid = { version = "1.21", features = ["v4"] }
wami-core = { path = "../../wami-core" }
wami-provider = { path = "../../wami-provider" }

